# Generated by Django 4.2.7 on 2024-12-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
