# Generated by Django 4.2.7 on 2024-12-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
