# Generated by Django 4.2.7 on 2024-12-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
    ]
