# Generated by Django 4.2.7 on 2024-12-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('correction', 'Исправление'), ('feedback', 'Обратная связь'), ('commendation', 'Похвала'), ('criticism', 'Критика')], default='feedback', max_length=50),
        ),
    ]
