# Generated by Django 4.2.7 on 2024-12-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_note_addressed_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='project',
        ),
    ]
