# Generated by Django 4.2.7 on 2024-12-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('открыта', 'Открыта'), ('в работе', 'В работе'), ('выполнена', 'Выполнена'), ('требуется проверка', 'Требуется проверка')], default='new', max_length=20),
        ),
    ]
