# Generated by Django 4.2.7 on 2024-12-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='marked_as_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('открыта', 'Открыта'), ('в работе', 'В работе'), ('выполнена', 'Выполнена'), ('требуется проверка', 'Требуется проверка')], default='открыта', max_length=20),
        ),
    ]
