# Generated by Django 4.2.7 on 2024-12-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_marked_as_completed_at_task_status_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_necessary',
            field=models.BooleanField(default=False, verbose_name='Необходимо'),
            preserve_default=False,
        ),
    ]
